locals {
  # Azure location to timezone mapping (alphabetically ordered)
  # Using Windows timezone identifiers as used by Azure/Terraform providers
  azure_location_timezone_map = {
    "australiacentral"    = "AUS Central Standard Time"
    "australiacentral2"   = "AUS Central Standard Time"
    "australiaeast"       = "AUS Eastern Standard Time"
    "australiasoutheast"  = "AUS Eastern Standard Time"
    "australiawest"       = "W. Australia Standard Time"
    "brazilsouth"         = "E. South America Standard Time"
    "canadacentral"       = "Eastern Standard Time"
    "canadaeast"          = "Eastern Standard Time"
    "centralindia"        = "India Standard Time"
    "centralus"           = "Central Standard Time"
    "centraluseuap"       = "Central Standard Time"
    "chinaeast"           = "China Standard Time"
    "chinaeast2"          = "China Standard Time"
    "chinaeast3"          = "China Standard Time"
    "chinanorth"          = "China Standard Time"
    "chinanorth2"         = "China Standard Time"
    "chinanorth3"         = "China Standard Time"
    "chinanorth4"         = "China Standard Time"
    "chinasouth"          = "China Standard Time"
    "chinasouth2"         = "China Standard Time"
    "chinasoutheast"      = "China Standard Time"
    "chinawest"           = "China Standard Time"
    "chinawest2"          = "China Standard Time"
    "eastasia"            = "China Standard Time"
    "eastus"              = "Eastern Standard Time"
    "eastus2"             = "Eastern Standard Time"
    "eastus2euap"         = "Eastern Standard Time"
    "eastus3"             = "Eastern Standard Time"
    "francecentral"       = "Romance Standard Time"
    "francesouth"         = "Romance Standard Time"
    "germanywestcentral"  = "W. Europe Standard Time"
    "germanynorth"        = "W. Europe Standard Time"
    "israelcentral"       = "Israel Standard Time"
    "italynorth"          = "W. Europe Standard Time"
    "japaneast"           = "Tokyo Standard Time"
    "japanwest"           = "Tokyo Standard Time"
    "jioindiacentral"     = "India Standard Time"
    "jioindiawest"        = "India Standard Time"
    "koreacentral"        = "Korea Standard Time"
    "koreasouth"          = "Korea Standard Time"
    "malaysiasouth"       = "Singapore Standard Time"
    "mexicocentral"       = "Central Standard Time"
    "newzealandnorth"     = "New Zealand Standard Time"
    "northcentralus"      = "Central Standard Time"
    "northeurope"         = "GMT Standard Time"
    "norwayeast"          = "W. Europe Standard Time"
    "norwaywest"          = "W. Europe Standard Time"
    "polandcentral"       = "Central European Standard Time"
    "qatarcentral"        = "Arab Standard Time"
    "southafricanorth"    = "South Africa Standard Time"
    "southafricawest"     = "South Africa Standard Time"
    "southcentralus"      = "Central Standard Time"
    "southeastasia"       = "Singapore Standard Time"
    "southeastus"         = "Eastern Standard Time"
    "southeaststus"       = "Eastern Standard Time"
    "southindia"          = "India Standard Time"
    "spaincentral"        = "Romance Standard Time"
    "swedencentral"       = "W. Europe Standard Time"
    "switzerlandnorth"    = "W. Europe Standard Time"
    "switzerlandwest"     = "W. Europe Standard Time"
    "taiwannorth"         = "Taipei Standard Time"
    "taiwannorthwest"     = "Taipei Standard Time"
    "uaenorth"            = "Arabian Standard Time"
    "uksouth"             = "GMT Standard Time"
    "ukwest"              = "GMT Standard Time"
    "usdodcentral"        = "Central Standard Time"
    "usdodeast"           = "Eastern Standard Time"
    "usgioviowa"          = "Central Standard Time"
    "usgovarizona"        = "US Mountain Standard Time"
    "usgoveast"           = "Eastern Standard Time"
    "usgovsouthwest"      = "Mountain Standard Time"
    "usgovtexas"          = "Central Standard Time"
    "usgovvirginia"       = "Eastern Standard Time"
    "usgovwest"           = "Pacific Standard Time"
    "westcentralus"       = "Mountain Standard Time"
    "westeurope"          = "W. Europe Standard Time"
    "westindia"           = "India Standard Time"
    "westus"              = "Pacific Standard Time"
    "westus2"             = "Pacific Standard Time"
    "westus3"             = "Pacific Standard Time"
    "westus4"             = "Pacific Standard Time"
  }
}

# Example usage:
# time_zone = local.azure_location_timezone_map[var.location]
# 
# Or with a fallback:
# time_zone = lookup(local.azure_location_timezone_map, var.location, "UTC")